name: "Tests"

#on: [pull_request]
# Triggers the workflow on push or pull request events but only for the "main" branch
on:
 pull_request:
 workflow_dispatch:

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template_dir: '.github/PULL_REQUEST_TEMPLATE/'
          mapping: 'feature=feature/,feat/;bugfix=fix/,bugfix/'
          default: 'feature'
